#!/usr/bin/env bash
# Regenerate the Cloudflare IP snippets used by nginx/transznemu.conf.
# Fetches the current published ranges and rewrites both snippet files.
# Run, then: sudo nginx -t && sudo systemctl reload nginx
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
snip="$here/nginx/snippets"
date_tag="$(date +%Y-%m)"

v4="$(curl -fsS https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS https://www.cloudflare.com/ips-v6)"

[ -n "$v4" ] && [ -n "$v6" ] || { echo "empty IP list from Cloudflare, aborting" >&2; exit 1; }

gen() {
    # $1 = directive (allow | set_real_ip_from), $2 = output file
    {
        echo "# Cloudflare IP ranges - generated by scripts/update-cloudflare-ips.sh."
        echo "# Source: https://www.cloudflare.com/ips/  (fetched $date_tag)"
        echo
        echo "# IPv4"
        while IFS= read -r cidr; do [ -n "$cidr" ] && echo "$1 $cidr;"; done <<< "$v4"
        echo
        echo "# IPv6"
        while IFS= read -r cidr; do [ -n "$cidr" ] && echo "$1 $cidr;"; done <<< "$v6"
    } > "$2"
    echo "wrote $2"
}

gen "allow"            "$snip/cloudflare-allow.conf"
gen "set_real_ip_from" "$snip/cloudflare-realip.conf"
